name: Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-publish-symbols:
    uses: kirandevops1993/PUBLISH-REUSABLE-/.github/workflows/publish-reusable.yml@main
    with:
      SymbolsPath: '/path/to/symbol/store'
      SearchPattern: '**/bin/**/*.pdb'
      SymbolsFolder: '/path/to/symbols/folder'
      SkipIndexing: false
      WarnIfNotIndexed: true
      MaxWaitTime: '30'
      SymbolsProduct: 'MyProduct'
      SymbolsVersion: '1.0.0'
    
